#!/usr/bin/env bash

set -euo pipefail

RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
BLUE='\033[0;34m'
NC='\033[0m'

log_info() { echo -e "${GREEN}[INFO]${NC} $1"; }
log_warn() { echo -e "${YELLOW}[WARN]${NC} $1"; }
log_error() { echo -e "${RED}[ERROR]${NC} $1"; }
log_step() { echo -e "${BLUE}[STEP]${NC} $1"; }

SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"
PROJECT_DIR="$SCRIPT_DIR"
LOGS_DIR="$PROJECT_DIR/logs"
CONFIG_DIR="$PROJECT_DIR/config"
CONFIG_FILE="$PROJECT_DIR/setup.config"
ENV_FILE="$PROJECT_DIR/.env"
ENV_LOCAL_FILE="$PROJECT_DIR/.env.local"
RUST_AGENT_DIR="$PROJECT_DIR/rust-agent"
RUST_BIN_PATH="$RUST_AGENT_DIR/target/release/presence-tracker-rs"
AGENT_CONFIG_FILE="$CONFIG_DIR/agent.toml"
BLUETOOTH_DISCOVERABLE_SCRIPT="/usr/local/bin/bluetooth-discoverable"

CURRENT_USER="$USER"
USER_HOME="$HOME"

BLUETOOTH_NAME="Presence Tracker"
DEPLOYMENT_MODE="convex"
SELF_HOSTED_URL=""
SELF_HOSTED_ADMIN_KEY=""
FRONTEND_URL=""

CLI_ACTION=""
CLI_NON_INTERACTIVE=false
CLI_BLUETOOTH_NAME=""
CLI_DEPLOYMENT_MODE=""
CLI_SELF_HOSTED_URL=""
CLI_SELF_HOSTED_ADMIN_KEY=""
CLI_FRONTEND_URL=""
CLI_SKIP_DEPLOY=false

mkdir -p "$LOGS_DIR" "$CONFIG_DIR"

print_usage() {
  cat << USAGE
Usage: ./setup.sh [options]

Actions:
  --full-install
  --update-config
  --redeploy-backend
  --restart-services
  --make-discoverable

Options:
  --bluetooth-name <name>
  --deployment-mode <convex|selfhosted|none>
  --self-hosted-url <url>
  --self-hosted-admin-key <key>
  --frontend-url <url>
  --skip-deploy
  --non-interactive
  --help
USAGE
}

parse_args() {
  while [[ $# -gt 0 ]]; do
    case "$1" in
      --full-install) CLI_ACTION="full_install"; shift ;;
      --update-config) CLI_ACTION="update_config"; shift ;;
      --redeploy-backend) CLI_ACTION="redeploy_backend"; shift ;;
      --restart-services) CLI_ACTION="restart_services_menu"; shift ;;
      --make-discoverable) CLI_ACTION="make_discoverable_menu"; shift ;;
      --bluetooth-name) CLI_BLUETOOTH_NAME="$2"; shift 2 ;;
      --deployment-mode)
        CLI_DEPLOYMENT_MODE="$2"
        case "$CLI_DEPLOYMENT_MODE" in
          convex|selfhosted|none) ;;
          *) log_error "Invalid deployment mode: $CLI_DEPLOYMENT_MODE"; exit 1 ;;
        esac
        shift 2
        ;;
      --self-hosted-url) CLI_SELF_HOSTED_URL="$2"; shift 2 ;;
      --self-hosted-admin-key) CLI_SELF_HOSTED_ADMIN_KEY="$2"; shift 2 ;;
      --frontend-url) CLI_FRONTEND_URL="$2"; shift 2 ;;
      --skip-deploy) CLI_SKIP_DEPLOY=true; shift ;;
      --non-interactive) CLI_NON_INTERACTIVE=true; shift ;;
      --help|-h) print_usage; exit 0 ;;
      *) log_error "Unknown argument: $1"; print_usage; exit 1 ;;
    esac
  done
}

load_config() {
  if [[ -f "$CONFIG_FILE" ]]; then
    # shellcheck disable=SC1090
    source "$CONFIG_FILE"
    log_info "Loaded saved config from $CONFIG_FILE"
  fi
}

save_config() {
  log_step "Saving setup config"
  {
    echo "# Auto-generated by setup.sh"
    printf 'BLUETOOTH_NAME=%q\n' "$BLUETOOTH_NAME"
    printf 'DEPLOYMENT_MODE=%q\n' "$DEPLOYMENT_MODE"
    printf 'SELF_HOSTED_URL=%q\n' "$SELF_HOSTED_URL"
    printf 'SELF_HOSTED_ADMIN_KEY=%q\n' "$SELF_HOSTED_ADMIN_KEY"
    printf 'FRONTEND_URL=%q\n' "$FRONTEND_URL"
    printf 'CONFIG_TIMESTAMP=%q\n' "$(date +%s)"
  } > "$CONFIG_FILE"
}

ensure_env_file() {
  if [[ ! -f "$ENV_FILE" ]]; then
    if [[ -f "$PROJECT_DIR/.env.example" ]]; then
      cp "$PROJECT_DIR/.env.example" "$ENV_FILE"
      log_info "Created .env from .env.example"
    else
      touch "$ENV_FILE"
      log_warn "Created empty .env (no .env.example found)"
    fi
  fi
  [[ -f "$ENV_LOCAL_FILE" ]] || touch "$ENV_LOCAL_FILE"
}

escape_env_value() {
  local v="$1"
  v="${v//\\/\\\\}"
  v="${v//\"/\\\"}"
  printf '%s' "$v"
}

set_env_var() {
  local file="$1"
  local key="$2"
  local value="$(escape_env_value "$3")"
  local line="${key}=\"${value}\""
  if grep -qE "^${key}=" "$file"; then
    sed -i "s|^${key}=.*|${line}|" "$file"
  else
    echo "$line" >> "$file"
  fi
}

remove_env_var() {
  local file="$1"
  local key="$2"
  sed -i "/^${key}=/d" "$file"
}

update_env_files() {
  log_step "Syncing .env and .env.local"

  for file in "$ENV_FILE" "$ENV_LOCAL_FILE"; do
    set_env_var "$file" "BLUETOOTH_NAME" "$BLUETOOTH_NAME"
    set_env_var "$file" "DEPLOYMENT_MODE" "$DEPLOYMENT_MODE"

    if [[ "$DEPLOYMENT_MODE" == "selfhosted" ]]; then
      set_env_var "$file" "CONVEX_URL_MODE" "selfhosted"
      set_env_var "$file" "CONVEX_SELF_HOSTED_URL" "$SELF_HOSTED_URL"
      set_env_var "$file" "CONVEX_DEPLOYMENT_URL" "$SELF_HOSTED_URL"
      if [[ -n "$SELF_HOSTED_ADMIN_KEY" ]]; then
        set_env_var "$file" "CONVEX_SELF_HOSTED_ADMIN_KEY" "$SELF_HOSTED_ADMIN_KEY"
      else
        remove_env_var "$file" "CONVEX_SELF_HOSTED_ADMIN_KEY"
      fi
      if [[ -n "$FRONTEND_URL" ]]; then
        set_env_var "$file" "FRONTEND_URL" "$FRONTEND_URL"
      fi
      remove_env_var "$file" "CONVEX_DEPLOYMENT"
      remove_env_var "$file" "CONVEX_DEPLOY_KEY"
    else
      set_env_var "$file" "CONVEX_URL_MODE" "convex"
      remove_env_var "$file" "CONVEX_SELF_HOSTED_URL"
      remove_env_var "$file" "CONVEX_SELF_HOSTED_ADMIN_KEY"
    fi
  done
}

prompt_with_default() {
  local prompt="$1"
  local default="$2"
  local value=""

  if [[ "$CLI_NON_INTERACTIVE" == true ]]; then
    printf '%s' "$default"
    return 0
  fi

  read -r -p "$prompt [$default]: " value
  if [[ -z "$value" ]]; then
    printf '%s' "$default"
  else
    printf '%s' "$value"
  fi
}

prompt_bluetooth_name() {
  local default_name="$BLUETOOTH_NAME"
  if [[ -n "$CLI_BLUETOOTH_NAME" ]]; then
    BLUETOOTH_NAME="$CLI_BLUETOOTH_NAME"
  else
    BLUETOOTH_NAME="$(prompt_with_default "Bluetooth device name" "$default_name")"
  fi
}

prompt_deployment_mode() {
  if [[ -n "$CLI_DEPLOYMENT_MODE" ]]; then
    DEPLOYMENT_MODE="$CLI_DEPLOYMENT_MODE"
    return 0
  fi

  if [[ "$CLI_NON_INTERACTIVE" == true ]]; then
    DEPLOYMENT_MODE="${DEPLOYMENT_MODE:-convex}"
    return 0
  fi

  local current="$DEPLOYMENT_MODE"
  echo ""
  echo "Choose backend deployment mode:"
  echo "  1) Convex cloud"
  echo "  2) Convex self-hosted"
  echo "  3) Skip backend setup"
  local choice
  read -r -p "Select [1-3] (default based on current: $current): " choice

  case "$choice" in
    1) DEPLOYMENT_MODE="convex" ;;
    2) DEPLOYMENT_MODE="selfhosted" ;;
    3) DEPLOYMENT_MODE="none" ;;
    "") DEPLOYMENT_MODE="$current" ;;
    *) log_warn "Invalid selection, keeping $current" ;;
  esac
}

prompt_self_hosted_values() {
  [[ "$DEPLOYMENT_MODE" == "selfhosted" ]] || return 0

  if [[ -n "$CLI_SELF_HOSTED_URL" ]]; then
    SELF_HOSTED_URL="$CLI_SELF_HOSTED_URL"
  else
    SELF_HOSTED_URL="$(prompt_with_default "Self-hosted Convex URL" "${SELF_HOSTED_URL:-http://127.0.0.1:3210}")"
  fi
  SELF_HOSTED_URL="${SELF_HOSTED_URL%/}"

  if [[ -n "$CLI_SELF_HOSTED_ADMIN_KEY" ]]; then
    SELF_HOSTED_ADMIN_KEY="$CLI_SELF_HOSTED_ADMIN_KEY"
  elif [[ "$CLI_NON_INTERACTIVE" == false ]]; then
    SELF_HOSTED_ADMIN_KEY="$(prompt_with_default "Self-hosted Convex admin key (optional)" "$SELF_HOSTED_ADMIN_KEY")"
  fi

  if [[ -n "$CLI_FRONTEND_URL" ]]; then
    FRONTEND_URL="$CLI_FRONTEND_URL"
  else
    FRONTEND_URL="$(prompt_with_default "Frontend URL" "${FRONTEND_URL:-$SELF_HOSTED_URL}")"
  fi
  FRONTEND_URL="${FRONTEND_URL%/}"
}

install_system_dependencies() {
  log_step "Installing system packages"
  sudo apt update
  sudo apt install -y \
    bluez bluez-tools bluetooth \
    build-essential pkg-config libdbus-1-dev libglib2.0-dev \
    curl git ca-certificates
}

ensure_bluetooth_service() {
  log_step "Ensuring bluetooth service"
  sudo systemctl enable bluetooth >/dev/null 2>&1 || true
  sudo systemctl restart bluetooth
}

configure_bluetooth_discoverable() {
  log_step "Configuring bluetooth adapter"
  log_info "Applying adapter settings (this can take up to ~30 seconds)"
  if ! command -v bluetoothctl >/dev/null 2>&1; then
    log_error "bluetoothctl not found"
    return 1
  fi

  btctl_quick() {
    timeout 5s sudo bluetoothctl --timeout 3 "$@" >/dev/null 2>&1 || true
  }

  btctl_quick power on
  btctl_quick discoverable on
  btctl_quick pairable on
  btctl_quick discoverable-timeout 0
  if timeout 5s bluetoothctl help 2>/dev/null | grep -q "pairable-timeout"; then
    btctl_quick pairable-timeout 0
  fi
  btctl_quick agent NoInputNoOutput
  btctl_quick default-agent
  btctl_quick system-alias "$BLUETOOTH_NAME"

  echo "PRETTY_HOSTNAME=$BLUETOOTH_NAME" | sudo tee /etc/machine-info >/dev/null
  log_info "Bluetooth adapter configured for pairable/discoverable mode"
}

install_node_if_missing() {
  if command -v node >/dev/null 2>&1 && command -v npm >/dev/null 2>&1; then
    return 0
  fi
  log_step "Installing Node.js LTS"
  curl -fsSL https://deb.nodesource.com/setup_lts.x | sudo -E bash -
  sudo apt install -y nodejs
}

install_bun_if_missing() {
  if command -v bun >/dev/null 2>&1; then
    return 0
  fi
  log_step "Installing Bun"
  curl -fsSL https://bun.sh/install | bash
  export BUN_INSTALL="$HOME/.bun"
  export PATH="$BUN_INSTALL/bin:$PATH"
}

install_rust_if_missing() {
  if command -v cargo >/dev/null 2>&1; then
    return 0
  fi
  log_step "Installing Rust toolchain"
  curl https://sh.rustup.rs -sSf | sh -s -- -y
}

source_runtime_paths() {
  if [[ -f "$HOME/.cargo/env" ]]; then
    # shellcheck disable=SC1090
    source "$HOME/.cargo/env"
  fi
  export BUN_INSTALL="${BUN_INSTALL:-$HOME/.bun}"
  export PATH="$BUN_INSTALL/bin:$PATH"
}

install_project_dependencies() {
  log_step "Installing project dependencies"
  source_runtime_paths

  if [[ -f "$PROJECT_DIR/package.json" ]]; then
    bun install
  fi

  if [[ ! -f "$RUST_AGENT_DIR/Cargo.toml" ]]; then
    log_error "Missing rust-agent/Cargo.toml"
    exit 1
  fi

  (cd "$RUST_AGENT_DIR" && cargo build --release)
}

configure_l2ping_permissions() {
  log_step "Configuring l2ping permissions"
  if command -v l2ping >/dev/null 2>&1; then
    sudo setcap cap_net_raw+ep "$(command -v l2ping)" || true
  fi
}

write_agent_config() {
  log_step "Writing $AGENT_CONFIG_FILE"

  local convex_url=""
  local admin_key=""

  convex_url="$(grep -E '^CONVEX_SELF_HOSTED_URL=' "$ENV_FILE" | tail -1 | cut -d '=' -f2- | tr -d '"')"
  if [[ -z "$convex_url" ]]; then
    convex_url="$(grep -E '^CONVEX_DEPLOYMENT_URL=' "$ENV_FILE" | tail -1 | cut -d '=' -f2- | tr -d '"')"
  fi
  admin_key="$(grep -E '^CONVEX_SELF_HOSTED_ADMIN_KEY=' "$ENV_FILE" | tail -1 | cut -d '=' -f2- | tr -d '"')"

  cat > "$AGENT_CONFIG_FILE" << CFG
[convex]
deployment_url = "$convex_url"
admin_key = "$admin_key"

[presence]
polling_interval_seconds = 15
absent_threshold = 3
grace_period_seconds = 300

[bluetooth]
l2ping_timeout_seconds = 2
l2ping_count = 1
connect_probe_timeout_seconds = 3
command_timeout_seconds = 10
audio_block_uuids = [
  "00001108-0000-1000-8000-00805f9b34fb",
  "0000110a-0000-1000-8000-00805f9b34fb",
  "0000110b-0000-1000-8000-00805f9b34fb",
  "0000110c-0000-1000-8000-00805f9b34fb",
  "0000110d-0000-1000-8000-00805f9b34fb",
  "0000110e-0000-1000-8000-00805f9b34fb",
  "0000110f-0000-1000-8000-00805f9b34fb",
  "00001112-0000-1000-8000-00805f9b34fb",
  "0000111e-0000-1000-8000-00805f9b34fb",
  "0000111f-0000-1000-8000-00805f9b34fb",
]

[logging]
log_file = "logs/presence_tracker.log"
max_lines = 1000

[paths]
state_file = "config/agent_state.json"
CFG
}

install_discoverable_script() {
  log_step "Installing bluetooth discoverable helper"
sudo tee "$BLUETOOTH_DISCOVERABLE_SCRIPT" >/dev/null << SCRIPT
#!/usr/bin/env bash
set -e
timeout 5s bluetoothctl --timeout 3 power on >/dev/null 2>&1 || true
timeout 5s bluetoothctl --timeout 3 discoverable on >/dev/null 2>&1 || true
timeout 5s bluetoothctl --timeout 3 pairable on >/dev/null 2>&1 || true
timeout 5s bluetoothctl --timeout 3 discoverable-timeout 0 >/dev/null 2>&1 || true
if timeout 5s bluetoothctl help 2>/dev/null | grep -q "pairable-timeout"; then
  timeout 5s bluetoothctl --timeout 3 pairable-timeout 0 >/dev/null 2>&1 || true
fi
timeout 5s bluetoothctl --timeout 3 agent NoInputNoOutput >/dev/null 2>&1 || true
timeout 5s bluetoothctl --timeout 3 default-agent >/dev/null 2>&1 || true
SCRIPT
  sudo chmod +x "$BLUETOOTH_DISCOVERABLE_SCRIPT"
}

cleanup_legacy_services() {
  log_step "Cleaning up legacy Python-era services"

  local legacy_units=(
    "bluetooth-agent.service"
    "presence-tracker-python.service"
    "presence-tracker-agent.service"
  )

  local unit
  for unit in "${legacy_units[@]}"; do
    sudo systemctl disable --now "$unit" 2>/dev/null || true
    sudo rm -f "/etc/systemd/system/$unit" 2>/dev/null || true
    sudo rm -f "/lib/systemd/system/$unit" 2>/dev/null || true
  done
}

generate_services() {
  log_step "Generating systemd units"

  sudo tee /etc/systemd/system/presence-tracker.service >/dev/null << UNIT
[Unit]
Description=Presence Tracker - Bluetooth Device Monitoring Service
After=bluetooth.target network-online.target
Wants=bluetooth.target

[Service]
Type=simple
User=root
Group=bluetooth
WorkingDirectory=$PROJECT_DIR
EnvironmentFile=$ENV_FILE
Environment="PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:$HOME/.cargo/bin:$HOME/.bun/bin"
ExecStart=$RUST_BIN_PATH --config $AGENT_CONFIG_FILE
Restart=always
RestartSec=10
StandardOutput=journal
StandardError=journal

[Install]
WantedBy=multi-user.target
UNIT

  sudo tee /etc/systemd/system/bluetooth-discoverable.service >/dev/null << UNIT
[Unit]
Description=Presence Tracker Bluetooth Discoverable Service
After=bluetooth.target
Wants=bluetooth.target

[Service]
Type=oneshot
ExecStart=$BLUETOOTH_DISCOVERABLE_SCRIPT
RemainAfterExit=yes

[Install]
WantedBy=multi-user.target
UNIT
}

deploy_backend() {
  [[ "$CLI_SKIP_DEPLOY" == true ]] && { log_info "Skipping backend deploy (--skip-deploy)"; return 0; }
  [[ "$DEPLOYMENT_MODE" == "none" ]] && { log_info "Skipping backend deploy (mode=none)"; return 0; }

  source_runtime_paths

  if ! command -v bunx >/dev/null 2>&1; then
    log_warn "bunx not found; skipping backend deploy"
    return 0
  fi

  if [[ "$DEPLOYMENT_MODE" == "convex" ]]; then
    log_step "Deploying Convex cloud backend"
    if [[ "$CLI_NON_INTERACTIVE" == false ]]; then
      bunx convex dev --configure
    fi
    bunx convex deploy
    return 0
  fi

  if [[ "$DEPLOYMENT_MODE" == "selfhosted" ]]; then
    log_step "Deploying to self-hosted Convex"
    if [[ -z "$SELF_HOSTED_URL" ]]; then
      log_warn "Self-hosted URL missing; skipping self-hosted deploy"
      return 0
    fi

    export CONVEX_SELF_HOSTED_URL="$SELF_HOSTED_URL"
    if [[ -n "$SELF_HOSTED_ADMIN_KEY" ]]; then
      export CONVEX_SELF_HOSTED_ADMIN_KEY="$SELF_HOSTED_ADMIN_KEY"
    fi

    bunx convex deploy
  fi
}

restart_services() {
  log_step "Reloading and restarting services"
  source_runtime_paths

  if [[ ! -x "$RUST_BIN_PATH" ]]; then
    log_info "Rust binary missing, rebuilding"
    (cd "$RUST_AGENT_DIR" && cargo build --release)
  fi

  cleanup_legacy_services
  install_discoverable_script
  generate_services
  sudo systemctl daemon-reload
  sudo systemctl enable presence-tracker.service
  sudo systemctl enable bluetooth-discoverable.service
  sudo systemctl restart presence-tracker.service
  sudo rfkill unblock bluetooth || true
  sudo systemctl restart bluetooth
  sudo systemctl restart bluetooth-discoverable.service
}

prompt_runtime_settings() {
  prompt_bluetooth_name
  prompt_deployment_mode
  prompt_self_hosted_values
}

full_install() {
  log_info "Starting full install"

  if [[ "$EUID" -eq 0 ]]; then
    log_error "Run setup.sh as a regular user, not root"
    exit 1
  fi

  prompt_runtime_settings
  save_config
  ensure_env_file
  update_env_files

  install_system_dependencies
  ensure_bluetooth_service
  configure_bluetooth_discoverable

  install_node_if_missing
  install_bun_if_missing
  install_rust_if_missing
  install_project_dependencies

  configure_l2ping_permissions
  write_agent_config
  install_discoverable_script
  cleanup_legacy_services
  generate_services
  deploy_backend
  restart_services

  log_info "Setup completed"
  log_info "Bluetooth name: $BLUETOOTH_NAME"
  log_info "Deployment mode: $DEPLOYMENT_MODE"
  log_info "Service logs: sudo journalctl -u presence-tracker -f"
}

update_config() {
  log_info "Updating config only"
  prompt_runtime_settings
  save_config
  ensure_env_file
  update_env_files
  write_agent_config
  generate_services
}

redeploy_backend() {
  log_info "Redeploy backend"
  prompt_deployment_mode
  prompt_self_hosted_values
  save_config
  ensure_env_file
  update_env_files
  write_agent_config
  deploy_backend
  restart_services
}

restart_services_menu() {
  restart_services
}

make_discoverable_menu() {
  ensure_bluetooth_service
  configure_bluetooth_discoverable
  log_info "Bluetooth discoverable mode refreshed"
}

show_menu() {
  echo ""
  echo "=========================================="
  echo "  Presence Tracker Setup"
  echo "=========================================="
  echo "  1) Full Install"
  echo "  2) Update Config"
  echo "  3) Resetup/Redeploy Backend"
  echo "  4) Restart Services"
  echo "  5) Make Bluetooth Discoverable"
  echo "  6) Exit"
  echo "=========================================="
}

main_menu() {
  while true; do
    show_menu
    read -r -p "Select an option [1-6]: " choice
    case "$choice" in
      1) full_install; break ;;
      2) update_config ;;
      3) redeploy_backend ;;
      4) restart_services_menu ;;
      5) make_discoverable_menu ;;
      6) exit 0 ;;
      *) log_warn "Invalid option" ;;
    esac
  done
}

run_action_if_requested() {
  [[ -n "$CLI_ACTION" ]] || return 1

  case "$CLI_ACTION" in
    full_install) full_install ;;
    update_config) update_config ;;
    redeploy_backend) redeploy_backend ;;
    restart_services_menu) restart_services_menu ;;
    make_discoverable_menu) make_discoverable_menu ;;
    *) log_error "Unknown action: $CLI_ACTION"; exit 1 ;;
  esac
  return 0
}

main() {
  parse_args "$@"
  load_config
  ensure_env_file

  if run_action_if_requested; then
    exit 0
  fi

  main_menu
}

main "$@"
